<a href="https://colab.research.google.com/github/fabiomonte2/AP/blob/main/teste_preliminar_anteprojeto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [374]:
import numpy as np

import pandas as pd

from pandas import Series, DataFrame

from sklearn.model_selection import train_test_split

# Nova seção

In [375]:
data = pd.read_csv('vendas_homelist.csv')
data = df.replace(r'\W+', '', regex=True)


In [376]:
data.head()

ID  Numero_pedido  ... Preco_Total  Codigo_produto
0  14654545550          10027  ...         229             439
1  14654545550          10027  ...         877              84
2  14654545550          10027  ...         962             368
3  14654545550          10027  ...        1739             853
4  14654545550          10027  ...        1458             573

[5 rows x 20 columns]

In [377]:
import pandas as pd
data = pd.read_csv('vendas_homelist.csv')
data.dtypes

ID                 int64
Numero_pedido      int64
Data_compra       object
ID_contato         int64
Nome_cliente      object
Cpf_Cnpj          object
Endereco          object
Bairro            object
Municipio         object
Cep               object
Estado            object
E-mail            object
Telefone          object
ID_produto         int64
Descricao         object
Quantidade        object
Valor_uni         object
Desconto item     object
Preco_Total       object
Codigo_produto     int64
dtype: object

In [378]:
y = data['ID_produto']
y

0      14358672115
1      14358662976
2      14358670009
3      14358684476
4      14358676128
          ...     
967    14358698489
968    14358669855
969    14358681692
970    14358665341
971    14358698948
Name: ID_produto, Length: 972, dtype: int64

In [379]:
X = data.drop('ID_produto',axis=1)
X.columns

Index(['ID', 'Numero_pedido', 'Data_compra', 'ID_contato', 'Nome_cliente',
       'Cpf_Cnpj', 'Endereco', 'Bairro', 'Municipio', 'Cep', 'Estado',
       'E-mail', 'Telefone', 'Descricao', 'Quantidade', 'Valor_uni',
       'Desconto item', 'Preco_Total', 'Codigo_produto'],
      dtype='object')

In [380]:
for column in X.columns:
  print(f"{column:>12}: {len(set(X[column])):4} {X[column].dtype}")

          ID:   55 int64
Numero_pedido:   55 int64
 Data_compra:   21 object
  ID_contato:    8 int64
Nome_cliente:    8 object
    Cpf_Cnpj:    8 object
    Endereco:    8 object
      Bairro:    8 object
   Municipio:    2 object
         Cep:    8 object
      Estado:    1 object
      E-mail:    8 object
    Telefone:    8 object
   Descricao:  257 object
  Quantidade:  162 object
   Valor_uni:  275 object
Desconto item:    2 object
 Preco_Total:  447 object
Codigo_produto:  254 int64


In [381]:
indesejadas = ['Preco_Total']
Xdrop = X.drop(indesejadas,axis=1)
Xdrop.columns

Index(['ID', 'Numero_pedido', 'Data_compra', 'ID_contato', 'Nome_cliente',
       'Cpf_Cnpj', 'Endereco', 'Bairro', 'Municipio', 'Cep', 'Estado',
       'E-mail', 'Telefone', 'Descricao', 'Quantidade', 'Valor_uni',
       'Desconto item', 'Codigo_produto'],
      dtype='object')

In [382]:
Xnum = Xdrop.select_dtypes('number')
Xnum.columns

Index(['ID', 'Numero_pedido', 'ID_contato', 'Codigo_produto'], dtype='object')

In [383]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median') 
XnumLimpo = imputer.fit_transform(Xnum)
XnumLimpo

array([[1.46545456e+10, 1.00270000e+04, 1.45144577e+10, 4.39000000e+02],
       [1.46545456e+10, 1.00270000e+04, 1.45144577e+10, 8.40000000e+01],
       [1.46545456e+10, 1.00270000e+04, 1.45144577e+10, 3.68000000e+02],
       ...,
       [1.56534553e+10, 1.00810000e+04, 1.45144724e+10, 7.87000000e+02],
       [1.56534553e+10, 1.00810000e+04, 1.45144724e+10, 1.85000000e+02],
       [1.56534553e+10, 1.00810000e+04, 1.45144724e+10, 1.26100000e+03]])

In [384]:
for column in Xnum.columns:
  print(f"{column:>12}: {sum(Xnum[column].isnull())}")

          ID: 0
Numero_pedido: 0
  ID_contato: 0
Codigo_produto: 0


In [385]:
Xcat = Xdrop.select_dtypes('object')
Xcat.columns

Index(['Data_compra', 'Nome_cliente', 'Cpf_Cnpj', 'Endereco', 'Bairro',
       'Municipio', 'Cep', 'Estado', 'E-mail', 'Telefone', 'Descricao',
       'Quantidade', 'Valor_uni', 'Desconto item'],
      dtype='object')

In [386]:
for column in Xcat.columns:
  print(f"{column:>12}: {sum(Xcat[column].isnull())}")

 Data_compra: 0
Nome_cliente: 0
    Cpf_Cnpj: 0
    Endereco: 0
      Bairro: 0
   Municipio: 0
         Cep: 0
      Estado: 0
      E-mail: 0
    Telefone: 0
   Descricao: 0
  Quantidade: 0
   Valor_uni: 0
Desconto item: 0


In [387]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
XcatLimpo = imputer.fit_transform(Xcat)
XcatLimpo

array([['9/20/2021', 'Fernanda zani', '112.532.657-39', ..., '1',
        'R$ 2,29', '0'],
       ['9/20/2021', 'Fernanda zani', '112.532.657-39', ..., '1',
        'R$ 8,77', '0'],
       ['9/20/2021', 'Fernanda zani', '112.532.657-39', ..., '1',
        'R$ 9,62', '0'],
       ...,
       ['12/22/2021', 'Ana Carolina Vieira da rosa Andreao',
        '112.532.697-26', ..., '1', 'R$ 3,19', '0'],
       ['12/22/2021', 'Ana Carolina Vieira da rosa Andreao',
        '112.532.697-26', ..., '1', 'R$ 2,89', '0'],
       ['12/22/2021', 'Ana Carolina Vieira da rosa Andreao',
        '112.532.697-26', ..., '1', 'R$ 9,43', '0']], dtype=object)

In [388]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
XcatHot = encoder.fit_transform(XcatLimpo)
XcatHot

<972x776 sparse matrix of type '<class 'numpy.float64'>'
	with 13608 stored elements in Compressed Sparse Row format>

In [389]:
import numpy as np 
Xtratado = np.c_[XnumLimpo,XcatHot.toarray()]
Xtratado.shape

(972, 780)

In [390]:
import pandas as pd
train = pd.read_csv('vendas_homelist.csv')
test = pd.read_csv('test.csv')
test = df.replace(r'\W+', '', regex=True)
train.columns.isin(test.columns)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [391]:
# Remover as caracteristicas indesejáveis
from sklearn.base import BaseEstimator, TransformerMixin
class AtributosDesejados(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    self.colunasIndesejadas = ['Preco_Total']
    return self
  def transform(self, X, y=None):
    return X.drop(self.colunasIndesejadas,axis=1)

atributosDesejados = AtributosDesejados()
Xdrop = atributosDesejados.fit_transform(X)
Xdrop.columns

Index(['ID', 'Numero_pedido', 'Data_compra', 'ID_contato', 'Nome_cliente',
       'Cpf_Cnpj', 'Endereco', 'Bairro', 'Municipio', 'Cep', 'Estado',
       'E-mail', 'Telefone', 'Descricao', 'Quantidade', 'Valor_uni',
       'Desconto item', 'Codigo_produto'],
      dtype='object')

In [392]:
from sklearn.base import BaseEstimator, TransformerMixin
class AtributosNumericos(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    self.colunasNumericas = X.select_dtypes(include='number').columns
    return self
  def transform(self, X, y=None):
    return X[self.colunasNumericas]

atributosNumericos = AtributosNumericos()
Xnum = atributosNumericos.fit_transform(Xdrop)
Xnum.columns

Index(['ID', 'Numero_pedido', 'ID_contato', 'Codigo_produto'], dtype='object')

In [393]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

pipenum = Pipeline([
                ('atributos_numericos', AtributosNumericos()),
                ('imputer', SimpleImputer(strategy='median')),
                ('sacaler', StandardScaler())
])

XnumLimpo = pipenum.fit_transform(Xnum)
XnumLimpo

array([[-1.95556092, -1.74286421, -0.67202576, -0.44356032],
       [-1.95556092, -1.74286421, -0.67202576, -1.30585614],
       [-1.95556092, -1.74286421, -0.67202576, -0.61601948],
       ...,
       [ 1.49598167,  1.61565905, -0.67193891,  0.4017325 ],
       [ 1.49598167,  1.61565905, -0.67193891, -1.06052691],
       [ 1.49598167,  1.61565905, -0.67193891,  1.5530796 ]])

In [394]:
from sklearn.base import BaseEstimator, TransformerMixin
class AtributosCategoricos(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    self.colunasCategoricas = X.select_dtypes(include='object').columns
    return self
  def transform(self, X, y=None):
    return X[self.colunasCategoricas]

atributosCategoricos = AtributosCategoricos()
Xcat = atributosCategoricos.fit_transform(Xdrop)
Xcat.columns

Index(['Data_compra', 'Nome_cliente', 'Cpf_Cnpj', 'Endereco', 'Bairro',
       'Municipio', 'Cep', 'Estado', 'E-mail', 'Telefone', 'Descricao',
       'Quantidade', 'Valor_uni', 'Desconto item'],
      dtype='object')

In [395]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

pipecat = Pipeline([
                ('atributos_categoricos', AtributosCategoricos()),
                ('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

XcatLimpo = pipenum.fit_transform(Xdrop)
XcatLimpo

array([[-1.95556092, -1.74286421, -0.67202576, -0.44356032],
       [-1.95556092, -1.74286421, -0.67202576, -1.30585614],
       [-1.95556092, -1.74286421, -0.67202576, -0.61601948],
       ...,
       [ 1.49598167,  1.61565905, -0.67193891,  0.4017325 ],
       [ 1.49598167,  1.61565905, -0.67193891, -1.06052691],
       [ 1.49598167,  1.61565905, -0.67193891,  1.5530796 ]])

In [396]:
from sklearn.pipeline import FeatureUnion
unecaracteristicas = FeatureUnion([
      ('pipenum', pipenum),
      ('pipecat', pipecat)
])

Xtratado = unecaracteristicas.fit_transform(X)
Xtratado

<972x1227 sparse matrix of type '<class 'numpy.float64'>'
	with 18468 stored elements in Compressed Sparse Row format>

In [397]:
from sklearn.pipeline import Pipeline

preproc = Pipeline([
        ('unecaracteristicas', unecaracteristicas)
])

Xtratado = preproc.fit_transform(Xdrop)
Xtratado

<972x780 sparse matrix of type '<class 'numpy.float64'>'
	with 17496 stored elements in Compressed Sparse Row format>

In [398]:
# testando o modelo com o algoritmo de arvore de decisão
from sklearn.tree import DecisionTreeClassifier

pipetotal = Pipeline([
        ('preproc', preproc),
        ('arvore', DecisionTreeClassifier())             
])
from sklearn.model_selection import cross_validate
import numpy as np

scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

from sklearn.model_selection import GridSearchCV
parametros = {
    'arvore__max_depth': [None] + list(range(1,20,2)),
    'arvore__criterion': ['gini', 'entropy']
    }
modelo = GridSearchCV(pipetotal, param_grid=parametros)
scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])




/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


({'fit_time': array([0.15049791, 0.14759183, 0.14191914, 0.14601064, 0.14354491]),
  'score_time': array([0.01182437, 0.01126838, 0.01157832, 0.01152563, 0.01347113]),
  'test_score': array([0.78974359, 0.84615385, 0.83505155, 0.82474227, 0.84020619])},
 0.8271794871794871)

In [399]:
from sklearn.neighbors import KNeighborsClassifier

pipetotal = Pipeline([
        ('preproc', preproc),
        ('knn', KNeighborsClassifier())             
])
from sklearn.model_selection import cross_validate
import numpy as np

scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

from sklearn.model_selection import GridSearchCV
parametros = {
    'knn__max_depth': [None] + list(range(1,20,2)),
    'knn__criterion': ['gini', 'entropy']
    }
modelo = GridSearchCV(pipetotal, param_grid=parametros)
scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


({'fit_time': array([0.02469063, 0.02783918, 0.02402329, 0.03123355, 0.0237093 ]),
  'score_time': array([0.02405167, 0.02404475, 0.02468157, 0.0271337 , 0.02571392]),
  'test_score': array([0.35384615, 0.51794872, 0.53092784, 0.56185567, 0.45876289])},
 0.48466825270948977)

In [400]:
from sklearn.linear_model import Perceptron

pipetotal = Pipeline([
        ('preproc', preproc),
        ('perceptron', Perceptron())             
])
from sklearn.model_selection import cross_validate
import numpy as np

scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

from sklearn.model_selection import GridSearchCV
parametros = {
    'perceptron__max_depth': [None] + list(range(1,20,2)),
    'perceptron__criterion': ['gini', 'entropy']
    }
modelo = GridSearchCV(pipetotal, param_grid=parametros)
scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


({'fit_time': array([0.25343156, 0.24563384, 0.24542332, 0.25391054, 0.25663471]),
  'score_time': array([0.01413035, 0.01270914, 0.01423097, 0.01324749, 0.01499295]),
  'test_score': array([0.52307692, 0.71282051, 0.72680412, 0.75257732, 0.68556701])},
 0.6801691779011367)

In [401]:
from sklearn.linear_model import LogisticRegression

pipetotal = Pipeline([
        ('preproc', preproc),
        ('logisticreg', LogisticRegression())             
])
from sklearn.model_selection import cross_validate
import numpy as np

scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

from sklearn.model_selection import GridSearchCV
parametros = {
    'logisticreg__max_depth': [None] + list(range(1,20,2)),
    'logisticreg__criterion': ['gini', 'entropy']
    }
modelo = GridSearchCV(pipetotal, param_grid=parametros)
scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


({'fit_time': array([7.94344401, 8.37836695, 7.75193548, 7.65616107, 7.94341326]),
  'score_time': array([0.05581474, 0.02053499, 0.02170467, 0.02206063, 0.02916098]),
  'test_score': array([0.69230769, 0.79487179, 0.75257732, 0.80412371, 0.75773196])},
 0.7603224953740417)

In [402]:
from sklearn.ensemble import RandomForestClassifier

pipetotal = Pipeline([
        ('preproc', preproc),
        ('randonf', RandomForestClassifier())             
])
from sklearn.model_selection import cross_validate
import numpy as np

scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

from sklearn.model_selection import GridSearchCV
parametros = {
    'randonf__max_depth': [None] + list(range(1,20,2)),
    'randonf__criterion': ['gini', 'entropy']
    }
modelo = GridSearchCV(pipetotal, param_grid=parametros)
scores = cross_validate(pipetotal, X, y)
scores, np.mean(scores['test_score'])

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,


({'fit_time': array([0.6535902 , 0.65317702, 0.6802814 , 0.64203739, 0.65160394]),
  'score_time': array([0.0545907 , 0.06462383, 0.05604362, 0.05211854, 0.0525167 ]),
  'test_score': array([0.82051282, 0.83589744, 0.82474227, 0.80412371, 0.80927835])},
 0.8189109172614326)